# Site settings
title: "이력서 - 김혜선"
description: "이력서 - 김혜선"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "김혜선 Kim Hyeseon"
resume_title:                   "FrontEnd Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "rla9194@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-9988-9194"
resume_contact_address:         "contact Email"

resume_header_contact_info:     "010-9988-9194 • rla9194@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>1년차 프론트엔드 개발자 김혜선입니다. 주체적으로 일을 찾고 자신만의 길을 가는 사람이 성공할 수 있다고 생각합니다. 더 좋은 프로그램을 만들기 위해 공부하여 발전하는 개발자가 되고싶습니다.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/hyebbi/resume"
  resume_twitter_url:           "http://twitter.com/hyebbi"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://hyebbi.com"
  resume_medium_url:            "https://medium.com/@hyebbi"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
